export * from "./ICreateDocumentDto";
export * from "./IUpdateDocumentDto";
export * from "./ICreateCitizenDto";
export * from "./ICreateDocumentWithCitizenRequestDto";
export * from "./IUpdateCitizenDto";
export * from "./IFindOneWithCitizen";
export * from "./IFindAllPendingAndDerivedDocument";
export * from "./IFindAllInProgressDocument";
export * from "./IFindAllObservedDocument";
export * from "./IFindAllArchivedDocument";
export * from "./IFindByDocumentNumber"