export enum StatusDocumentEnum {
  PENDING_RECEPTION = "PENDING_RECEPTION",
  ATTENDED_DERIVED = "ATTENDED_DERIVED",
  IN_PROGRESS = "IN_PROGRESS",
  OBSERVED = "OBSERVED",
  ARCHIVED = "ARCHIVED",
}
